server:
  port: 8088

spring:
  datasource:                                 #数据源相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    password: 123456
  redis:
    # Redis的单机单实例
    database: 1
    host: 192.168.198.128
    port: 6379
    password: 123456
    # Redis 哨兵模式
#    database: 1
#    password: 123456
#    sentinel:
#      master: han-master
#      nodes: 192.168.198.128:26379,192.168.198.129:26379,192.168.198.130:26379,

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #在控制台打印sql语句（适用于开发环境, 生产环境大可不必）